apiVersion: v1
kind: Secret
metadata:
  name: acr-secret
type: Opaque
data:
  docker-server=testenvironmentapp.azurecr.io
  docker-username=testenvironmentapp
  docker-password=3EJwD+SjsALuFsL9cU6ocJSyWcQ0XfkI5mVVq+yX8c+ACRD2caiv